### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by ashinmarin** [juliusfriedman/net7mma#11]
I'm trying to build the repo. But I'm facing a couple of missing DLL problems such as Media.Common.dll, Media.Compression.dll and Media.Codec.dll. Please help me with this. I'm using Visual Studio 2019.

**Comment by gismofx** [comment]
@ashinmarin Have you gotten the solution to build all of the DLLs?  If I clean and build the solution, I have 83 errors. 82 are missing DLLs and last one is

```
Error	CS0206	A property or indexer may not be passed as an out or ref parameter	Media.Common	C:\Source\Repos\net7mma\Common\Extensions\SymbolExtensions.cs	328	Active
```

**Comment by juliusfriedman** [comment]
Try https://github.com/juliusfriedman/net7mma_core, I believe there were some issues moving the project from CodePlex but it should be building, most likely it had something to do with the Build Order of the projects in the solution.
