### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by ThorIrgens** [juliusfriedman/net7mma#13]
Hi Julius.

I am running into build problems with the mma and mma_core repositories.
I cannot build mma with Visual Studio/MSBuild, as there are folders with the same names (h264 and H264) which makes windows think there are changes in these files

- Codecs\Video\h264\SliceType.cs
- Codecs\Video\h264\NalUnitType.cs
- Codecs\Video\h264\SupplementalEncoderInformationType.cs
- Codecs\Video\mpeg4\ObjectTypeIndication.cs

Also, line 328 in SymbolExtensions.cs causes problems, but that I could just comment out as the variable is not used.

I can build mma_core with MSBuild, but the dll's don't produce the same result/functionality, so cannot replace the existing one with the ones made with core.

Do you have any good suggestion and tricks on how to build the net7mma solution?

Best regards
Thor

**Comment by juliusfriedman** [comment]
Thanks for your interest, you can check out the .net core version of the project here

https://github.com/juliusfriedman/net7mma_core

I haven't built this code in a while but it should still work, if you need help with this specific version let me know and I'll see what I can do.

It seems to build in the latest visual studio just fine I think?
