### ISSUE TITLE
OSX or Linux Support?

### ISSUE THREAD

**Issue by winkmichael** [juliusfriedman/net7mma#3]
Hello all, i've been trying to use this library on Mono on Linux and OSX and run into the same issue.

System.Net.Sockets.SocketOptionName 0x2 is not supported at TCP level 

My code is simple; 

Socket listenSocket = new Socket(AddressFamily.InterNetwork,                                     SocketType.Stream,                                     ProtocolType.Tcp); 
        
IPEndPoint ep = new IPEndPoint(IPAddress.Any, 1555);         

using (Media.Rtsp.RtspServer server = new Media.Rtsp.RtspServer(ep))        
 {             
 Media.Rtsp.Server.MediaTypes.RtspSource source = new Media.Rtsp.Server.MediaTypes.RtspSource("RTSP", "rtsp://192.168.1.10/");     
         server.TryAddMedia(source);         
         server.Start();        
 }

Does anyone have a suggestion how I can modify the library to not use the socket exclusively?

i've found this post here, that seems related; https://github.com/dotnet/corefx/issues/11292
I've tried upgrading mono to 4.8 and I've tried to use it with core 2.0 dotnet  with no luck

Thanks so much

**Comment by juliusfriedman** [comment]
Not really sure what I can do for you other than advise the use of an alternate configuration function for the socket which resuses most of the code minus the socket option which is giving you issues.

**Comment by winkmichael** [comment]
Common/Extensions/SocketExtensions.cs

Line 957

#if __MonoCS__
#else
socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel.Socket, System.Net.Sockets.SocketOptionName.ReuseAddress, true);
#endif
