### ISSUE TITLE
Decoding RTSP

### ISSUE THREAD

**Issue by yasserjarouf** [juliusfriedman/net7mma#9]
I'm not sure if you have implemented this but is there any way to get image in base64 format when the RtpFrame IsComplete?

**Comment by juliusfriedman** [comment]
See https://stackoverflow.com/questions/11743160/how-do-i-encode-and-decode-a-base64-string

You would need to get the bytes of the ToImage call which is only implemented for RFC2435Frame and then get the bytes for that image and pass the functions indicated in the link above.

**Comment by juliusfriedman** [comment]
btw you can also just pass the raw depacketized data to those functions as well which lends itself well to using WebSockets or other implementations without requiring the use of `ToImage`
